name: lint

on:
  pull_request:
    
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
        with:
          ignore_paths: deps
        env:
          SHELLCHECK_OPTS: -x
